tailscale, neovim, t3x curl fix

diff --git a/scripts/t3x-install b/scripts/t3x-install
--- a/scripts/t3x-install
+++ b/scripts/t3x-install
@@ -1,5 +1,10 @@
 #!/usr/bin/bash
 
+if ! command -v curl > /dev/null; then
+	echo "missing curl .. fixing it"
+	sudo apt install curl
+fi
+
 cd $HOME
 if [ ! -d t3x ]; then
 	echo "curl t3x/bootstrap.sh | bash -e"
